CREATE TABLE IF NOT EXISTS public.places (
  id serial PRIMARY KEY,
  google_place_id varchar(255) NULL UNIQUE,
  slug varchar(255) NULL UNIQUE,
  name varchar(255) NULL,
  is_active boolean NULL DEFAULT true,
  is_featured boolean NULL DEFAULT false,
  category_key varchar(255) NULL,
  super_category varchar(255) NULL,
  theme varchar(255) NULL,
  tagline varchar(255) NULL,
  short_description text NULL,
  long_description text NULL,
  address text NULL,
  latitude double precision NULL,
  longitude double precision NULL,
  photo_reference text NULL,
  photo_attribution text NULL,
  booking_url varchar(255) NULL,
  tts_audio_path varchar(255) NULL,
  sort_order integer NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
